name: VPNGate IP Check

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:       # Allow manual trigger

jobs:
  vpngate-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run VPNGate IP Check
        run: |
          python check_vpn.py

      - name: Commit and push results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add *.md
          git add *.html
          git add configs/
          git add README.md

          git commit -m "🤖 VPNGate update: $(date '+%Y-%m-%d %H:%M:%S')"
          git push
