name: VPNGate IP Check

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:

jobs:
  vpngate-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Pull latest changes from main
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull origin main --rebase

      - name: Run VPNGate IP Check and Generate Reports
        run: |
          python check_vpn.py > output.txt

      - name: Commit and push results
        run: |
          git add .
          git diff --cached --quiet || git commit -m "Add latest VPNGate IP results"
          git push origin main

      - name: Send results to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          content=$(head -c 1800 output.txt)  # Discord limit: 2000 chars
          echo "{\"content\": \"\`\`\`${content}\`\`\`\"}" > payload.json
          curl -H "Content-Type: application/json" -X POST -d @payload.json $DISCORD_WEBHOOK
