name: VPNGate IP Check

on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours
  workflow_dispatch:

jobs:
  vpngate-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install requests

      - name: Set up Git to use GITHUB_TOKEN
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Run VPNGate IP Check and Generate Reports
        run: python check_vpn.py

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "🤖 VPNGate update: $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin main
